/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMintsLab, IMintsLabInterface } from "../IMintsLab";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "ftype",
        type: "uint256",
      },
    ],
    name: "checkRoyality",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "governanceDetails",
    outputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        internalType: "address",
        name: "dev",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "govShare",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMintsLab__factory {
  static readonly abi = _abi;
  static createInterface(): IMintsLabInterface {
    return new utils.Interface(_abi) as IMintsLabInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMintsLab {
    return new Contract(address, _abi, signerOrProvider) as IMintsLab;
  }
}
