/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INFTShop, INFTShopInterface } from "../INFTShop";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "shop",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "lastOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "Owner",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "enum INFTShop.fileType",
        name: "ftype",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
    ],
    name: "createPost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INFTShop__factory {
  static readonly abi = _abi;
  static createInterface(): INFTShopInterface {
    return new utils.Interface(_abi) as INFTShopInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTShop {
    return new Contract(address, _abi, signerOrProvider) as INFTShop;
  }
}
