/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface INFTShopInterface extends utils.Interface {
  functions: {
    "createPost(uint256,uint8,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createPost",
    values: [BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;

  events: {
    "Owner(address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Owner"): EventFragment;
}

export type OwnerEvent = TypedEvent<
  [string, string, string],
  { shop: string; lastOwner: string; newOwner: string }
>;

export type OwnerEventFilter = TypedEventFilter<OwnerEvent>;

export interface INFTShop extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: INFTShopInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPost(
      price: BigNumberish,
      ftype: BigNumberish,
      tokenURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createPost(
    price: BigNumberish,
    ftype: BigNumberish,
    tokenURI: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPost(
      price: BigNumberish,
      ftype: BigNumberish,
      tokenURI: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Owner(address,address,address)"(
      shop?: null,
      lastOwner?: null,
      newOwner?: null
    ): OwnerEventFilter;
    Owner(shop?: null, lastOwner?: null, newOwner?: null): OwnerEventFilter;
  };

  estimateGas: {
    createPost(
      price: BigNumberish,
      ftype: BigNumberish,
      tokenURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPost(
      price: BigNumberish,
      ftype: BigNumberish,
      tokenURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
